# Generated by Django 4.2.3 on 2023-10-30 15:17

import awx.main.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('state', awx.main.fields.JSONBlob(blank=True, default=dict)),
                ('lock_info', awx.main.fields.JSONBlob(blank=True, default=dict)),
            ],
        ),
    ]
